[package]
name = "Drygon_Test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
drygon = { git = "https://github.com/NocturnalWisp/DryGon-Engine.git"}